name: Build TF container with TF version 0.14.11

on:
  push:
    branches: [master]
    
jobs:
  push_to_registry:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: $[{ secrets.DOCKER_HUB_USERNAME }]
          password: $[{ secrets.DOCKER_HUB_USERNAME }]
          
      - name: Setup Container Build
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-actions@v2
        with:
          context: .
          push: true
          tags: <>

      - name: Build Container Image
        run: |
          echo "Building Image"
          docker build -t dockerhub-username/rep-name:latest

      - name: Publish Image to hub
        run: |
          echo "Pushing image to hub"
          docker push dockerhub-username/rep-name:latest
